### ISSUE TITLE
You cannot select an entity with no drawable or collision attribute

### ISSUE THREAD

**Issue by NickDefo** [ild-games/duckling-legacy#348]
Occasionally you will need to delete the drawable attribute off of an entity with no collision (Usually to change the drawable type - A separate UX issue which could be addressed in issue [347](https://github.com/ild-games/duckling/issues/347) )  When that happens, you immediately lose focus on the entity that you are editing, and now have a null entity stuck in your map file that you cannot interact with.

If an entity does not have a drawable or collision attribute on it, we should draw some sort of custom image for it, like we do for cameras, so that we can still interact with it.

**Comment by tlein** [comment]
Closing, already documented in #87, feel free to add suggestions for the problem there.
