### ISSUE TITLE
Multi select with movement

### ISSUE THREAD

**Issue by tlein** [ild-games/duckling-legacy#92]
Change entity editor to a list of the entities selected possibly

**Comment by jimmcnulty41** [comment]
These are the expected interactions and their resulting actions

| Click Type | Selected Entity      | Movement Occurs? | Clear Selection on Mouse Down? | Select on mouse down? | Move Selection? | Select on Mouse up? | Deselect on Mouse up? | 
|------------|----------------------|------------------|--------------------------------|-----------------------|-----------------|---------------------|-----------------------| 
| Normal     | Already Selected     | Yes              | Yes                            | Yes                   | Yes             |                     |                       | 
| Normal     | Already Selected     |                  | Yes                            | Yes                   |                 |                     |                       | 
| Shift      | Already Selected     | Yes              |                                |                       | Yes             |                     |                       | 
| Shift      | Already Selected     |                  |                                |                       |                 |                     | Yes                   | 
| Normal     | Currently Unselected | Yes              | Yes                            | Yes                   | Yes             |                     |                       | 
| Normal     | Currently Unselected |                  | Yes                            | Yes                   |                 |                     |                       | 
| Shift      | Currently Unselected | Yes              |                                | Yes                   | Yes             |                     |                       | 
| Shift      | Currently Unselected |                  |                                | Yes                      |                 |                     |                       | 
| Normal     | None                 | Yes              | Yes                            |                       |                 | Yes                 |                       | 
| Normal     | None                 |                  |                                |                       |                 |                     |                       | 
| Shift      | None                 | Yes              |                                |                       |                 | Yes                 |                       | 
| Shift      | None                 |                  |                                |                       |                 |                     |                       |
